/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_B */
#define LED_B_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_0_INBUF_ENABLED 0u
#define LED_B_0_INIT_DRIVESTATE 0u
#define LED_B_0_INIT_MUXSEL 0u
#define LED_B_0_INPUT_SYNC 2u
#define LED_B_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_0_NUM 4u
#define LED_B_0_PORT GPIO_PRT12
#define LED_B_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_B_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_INBUF_ENABLED 0u
#define LED_B_INIT_DRIVESTATE 0u
#define LED_B_INIT_MUXSEL 0u
#define LED_B_INPUT_SYNC 2u
#define LED_B_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_NUM 4u
#define LED_B_PORT GPIO_PRT12
#define LED_B_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Sns */
#define CapSense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_0_INBUF_ENABLED 0u
#define CapSense_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_Sns_0_INIT_MUXSEL 0u
#define CapSense_Sns_0_INPUT_SYNC 2u
#define CapSense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_0_NUM 0u
#define CapSense_Sns_0_PORT GPIO_PRT9
#define CapSense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_INBUF_ENABLED 0u
#define CapSense_Sns_INIT_DRIVESTATE 1u
#define CapSense_Sns_INIT_MUXSEL 0u
#define CapSense_Sns_INPUT_SYNC 2u
#define CapSense_Sns_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_NUM 0u
#define CapSense_Sns_PORT GPIO_PRT9
#define CapSense_Sns_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Cmod */
#define CapSense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_0_INBUF_ENABLED 0u
#define CapSense_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_Cmod_0_INIT_MUXSEL 0u
#define CapSense_Cmod_0_INPUT_SYNC 2u
#define CapSense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_0_NUM 7u
#define CapSense_Cmod_0_PORT GPIO_PRT7
#define CapSense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_INBUF_ENABLED 0u
#define CapSense_Cmod_INIT_DRIVESTATE 1u
#define CapSense_Cmod_INIT_MUXSEL 0u
#define CapSense_Cmod_INPUT_SYNC 2u
#define CapSense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_NUM 7u
#define CapSense_Cmod_PORT GPIO_PRT7
#define CapSense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_CapSense_scl */
#define I2C_CapSense_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_CapSense_scl_0_INBUF_ENABLED 1u
#define I2C_CapSense_scl_0_INIT_DRIVESTATE 1u
#define I2C_CapSense_scl_0_INIT_MUXSEL 19u
#define I2C_CapSense_scl_0_INPUT_SYNC 2u
#define I2C_CapSense_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_CapSense_scl_0_NUM 0u
#define I2C_CapSense_scl_0_PORT GPIO_PRT10
#define I2C_CapSense_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_CapSense_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_CapSense_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_CapSense_scl_INBUF_ENABLED 1u
#define I2C_CapSense_scl_INIT_DRIVESTATE 1u
#define I2C_CapSense_scl_INIT_MUXSEL 19u
#define I2C_CapSense_scl_INPUT_SYNC 2u
#define I2C_CapSense_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_CapSense_scl_NUM 0u
#define I2C_CapSense_scl_PORT GPIO_PRT10
#define I2C_CapSense_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_CapSense_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_CapSense_sda */
#define I2C_CapSense_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_CapSense_sda_0_INBUF_ENABLED 1u
#define I2C_CapSense_sda_0_INIT_DRIVESTATE 1u
#define I2C_CapSense_sda_0_INIT_MUXSEL 19u
#define I2C_CapSense_sda_0_INPUT_SYNC 2u
#define I2C_CapSense_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_CapSense_sda_0_NUM 1u
#define I2C_CapSense_sda_0_PORT GPIO_PRT10
#define I2C_CapSense_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_CapSense_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_CapSense_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_CapSense_sda_INBUF_ENABLED 1u
#define I2C_CapSense_sda_INIT_DRIVESTATE 1u
#define I2C_CapSense_sda_INIT_MUXSEL 19u
#define I2C_CapSense_sda_INPUT_SYNC 2u
#define I2C_CapSense_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_CapSense_sda_NUM 1u
#define I2C_CapSense_sda_PORT GPIO_PRT10
#define I2C_CapSense_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_CapSense_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
