#!/bin/sh
# This script allows a 3rd party IDE to use cymcuelftool.exe to perform
# the post processing that is necessary to update the *.elf file
# generated by the linker into a complete memory image to use in
# programming the PSoC.
# NOTE: Please provide the path to the CyElfTool.
