# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\Mac\Data\VScode\GIT\Onethinx_Project_Examples\Example_DevKitLightSensor\Onethinx_Creator.cydsn\Onethinx_Creator.cyprj
# Date: Wed, 23 Nov 2022 15:33:14 GMT
#set_units -time ns
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyClk_LF} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyClk_HF0} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/hfclk_0}]]
create_clock -name {CyClk_Fast} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/fastclk}]]
create_clock -name {CyClk_Peri} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/periclk}]]
create_generated_clock -name {CyClk_Slow} -source [get_pins {ClockBlock/periclk}] -edges {1 2 3} [list [get_pins {ClockBlock/slowclk}]]
create_generated_clock -name {ADC_intSarClock} -source [get_pins {ClockBlock/periclk}] -edges {1 9 17} [list [get_pins {ClockBlock/ff_div_49}]]
create_clock -name {CyPeriClk_App} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/periclk_App}]]
create_clock -name {CyIMO} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/imo}]]


# Component constraints for \\Mac\Data\VScode\GIT\Onethinx_Project_Examples\Example_DevKitLightSensor\Onethinx_Creator.cydsn\TopDesign\TopDesign.cysch
# Project: \\Mac\Data\VScode\GIT\Onethinx_Project_Examples\Example_DevKitLightSensor\Onethinx_Creator.cydsn\Onethinx_Creator.cyprj
# Date: Wed, 23 Nov 2022 15:32:43 GMT
