/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_B */
#define LED_B_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_0_INBUF_ENABLED 0u
#define LED_B_0_INIT_DRIVESTATE 0u
#define LED_B_0_INIT_MUXSEL 0u
#define LED_B_0_INPUT_SYNC 2u
#define LED_B_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_0_NUM 4u
#define LED_B_0_PORT GPIO_PRT12
#define LED_B_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_B_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_INBUF_ENABLED 0u
#define LED_B_INIT_DRIVESTATE 0u
#define LED_B_INIT_MUXSEL 0u
#define LED_B_INPUT_SYNC 2u
#define LED_B_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_NUM 4u
#define LED_B_PORT GPIO_PRT12
#define LED_B_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_R */
#define LED_R_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_0_INBUF_ENABLED 0u
#define LED_R_0_INIT_DRIVESTATE 1u
#define LED_R_0_INIT_MUXSEL 3u
#define LED_R_0_INPUT_SYNC 2u
#define LED_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_0_NUM 5u
#define LED_R_0_PORT GPIO_PRT12
#define LED_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_R_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_INBUF_ENABLED 0u
#define LED_R_INIT_DRIVESTATE 1u
#define LED_R_INIT_MUXSEL 3u
#define LED_R_INPUT_SYNC 2u
#define LED_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_NUM 5u
#define LED_R_PORT GPIO_PRT12
#define LED_R_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
