@REM This script allows a 3rd party IDE to use cymcuelftool.exe to perform
@REM the post processing that is necessary to update the *.elf file
@REM generated by the linker into a complete memory image to use in
@REM programming the PSoC.
@REM NOTE: This script is auto generated. Do not modify.
